<?php
    $conn=mysqli_connect("localhost","root","","blogwebsite");
    mysqli_query($conn,"set names 'utf8'");//设定字符集
    $sql="select * from article where $w";
    $result=mysqli_query($conn,$sql);
    $rows=mysqli_num_rows($result);//返回结果中行的数目
    $pagesize=3;//设置每页显示多少条记录
    $pagecount=ceil($rows/$pagesize);//总页数,向上取整
    if($pagecount==0){
        $offset=0;
        $page=1;
        $pagecount=1;
    }
    $page=isset($_GET['page'])?intval($_GET['page']):1;
    if($page<1){
        $page=1;
    }
    if($page>$pagecount){
        $page=$pagecount;
    }
    $pageprev=$page-1;
    $pagenext=$page+1;
    if($pageprev==0){
        $pageprev=1;
    }
    if($pagenext>$pagecount){
        $pagenext=$pagecount;
    }
    $offset=($page-1)*$pagesize;
?>